### ISSUE TITLE
Add smart sidebar component

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#102]
Provide a default home for the ol-kit components, but not a required component for ol-kit map implementers.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
