### ISSUE TITLE
Popup disappearing after panning map

### ISSUE THREAD

**Issue by jcuker** [Bayer-Group/ol-kit#106]
I have found that a popup will disappear and then no longer appear if a map is scrolled while the popup is open. This persists even though a page refresh.

To re-produce: open a popup, drag the map right until you circumnavigate the map, and then try to open/close the popup.

- [Repo to reproduce](https://github.com/jcuker/ol-kit-bug)
- Example gif
![example gif](https://user-images.githubusercontent.com/19519115/83804975-a1408a00-a674-11ea-867a-4900639f31ff.gif)

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
