### ISSUE TITLE
Maybe highlight the bbox on clustered clicks/hover?

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#119]
this mapbox demo makes it obvious where the underlying bbox of the cluster is which is very nice ux: https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
