### ISSUE TITLE
Add option to select time attribute for the timeslider UI

### ISSUE THREAD

**Issue by glenselle** [Bayer-Group/ol-kit#127]
To make it easier to explore time enabled data, we should add a dropdown with suggested date attributes to choose from on a given layer by inspecting a feature. This would make it possible to switch between different time attributes and work with imported data.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
