### ISSUE TITLE
Make Style Layer UI respond to smaller container area

### ISSUE THREAD

**Issue by glenselle** [Bayer-Group/ol-kit#128]
The current `LayerStyler` component doesn't respond well to a smaller container. Here's one possible layout which is more readable and not as tight:
<img width="461" alt="Screen Shot 2020-06-25 at 6 02 06 PM" src="https://user-images.githubusercontent.com/1056932/85804111-6dee9980-b70e-11ea-9be1-1a8058cfdd8c.png">
<img width="463" alt="Screen Shot 2020-06-25 at 6 03 58 PM" src="https://user-images.githubusercontent.com/1056932/85804112-6dee9980-b70e-11ea-87cb-9e6d5276c777.png">

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
