### ISSUE TITLE
Animate time-enabled data with the timeslider

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#129]
To better track changes in time-enabled data over time (weather, covid, etc), it would be super cool to have a play button which would display changes without needing additional user input.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
