### ISSUE TITLE
Timeslider increment identifier (prop or calculation)

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#130]
The original use case the `<TimeSlider>` was written around involved planting seasons over multiple years...so to avoid over populating the slider with ticks, all data on the same day gets group into one tick. With more fine grained data (like hourly for example) this hardcode grouping ruins the visualization...allow an `increments` prop of `days`, `hours`, `minutes` etc. or somehow determine from the data the best increments to group on

**Comment by jcuker** [comment]
Following this - I would love to contribute a radar example using the enhanced time slider! Something similar to [this](https://jcuker.github.io/ol/7).

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
