### ISSUE TITLE
Enabling smart labels changes feature styles

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#131]
Before smart label toggle click:
![Screen Shot 2020-07-02 at 09 08 30](https://user-images.githubusercontent.com/37306038/86369177-b1339580-bc43-11ea-9d03-07ac60196b0e.png)

After smart label toggle click:
![Screen Shot 2020-07-02 at 09 08 42](https://user-images.githubusercontent.com/37306038/86369170-af69d200-bc43-11ea-8c8e-5d765b69d628.png)

Seems like feature opacity is being affected here. Also, it seems like `_ol_kit_...` properties are being added at this time, including `_ol_kit_feature_style`.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
