### ISSUE TITLE
Clone-able bootstrap app inside of ol-kit

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#154]
Maybe using git submodules, make ol-kit map app clone-able and runnable without the wrapping project

- [ ] Add package.json to app dir for ol-kit map specifically
- [ ] Update Getting Started guide

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
