### ISSUE TITLE
Add geospatial search / intersect capability

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#157]
For a data set loaded in memory, add ability to filter by geospatial intersection

Example:
"I want to see all the farmers within 30 miles of me."

turf has this built in
Does openlayers have this?

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
