### ISSUE TITLE
Sort filtered dataset by distance from point

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#158]
Filter and sort dataset by distance.

Example:
"What farmers are within 30 miles of me?"
Provide a list sorted by distance from point.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
