### ISSUE TITLE
Add Localization Capabilities

### ISSUE THREAD

**Issue by glenselle** [Bayer-Group/ol-kit#17]
We have support for overriding translations and adding other languages, but localization of numbers, dates and other such things is not in place. This issue captures the need to address this.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
