### ISSUE TITLE
Add "magnifier" view for zoomed-in popup

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#190]
Based on where your mouse is, show a tiny map in a popup that's zoomed into the pointer's location.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
