### ISSUE TITLE
Add a "regional context view" mini map

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#191]
When you're zoomed in, have a mini map display component that gives you context as to where you are in the world

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
