### ISSUE TITLE
SPIKE - Provider/MultiMap

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#192]
step 1:
- Ensure the `Map` component is not the same as the `Provider` -- keep separate

option 0:
- create specialized multi map components such as `MultiMapZoom` that takes `maps` and handles syncing between the two or `MultiMapFindLocation` -- any component not named `MultiMap` only ever takes a `map` prop

option 1:
- hoist map creation to `<Provider>` and `<Map map={map} />` only ever takes a map prop (does not create one)

option 2:
- never create a map in ol-kit; require an explicit prop to `<Provider map={createMap()}>` or `<Provider maps={[createMap(), createMap()]}>`

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
