### ISSUE TITLE
Add "Centroid" point option for polygon/circle features

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#193]
- [ ] "Add Centroid" as popup action
- [ ] Use turf utilities to calculate coords of centroid point feature
- [ ] Added as separate feature to the map that is not linked to the originating shape. (If originating shape is moved or edited, centroid feature does not follow)
- [ ] Add centroid feature to the Annotation layer
- [ ] Add tests

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
