### ISSUE TITLE
Add interactive code examples in documentation

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#198]

**Comment by UsmanAhmadSaeed** [comment]
This seems a fun project. Would love to do. Kindly give suggestions, guides, etc

**Comment by AtherBilal** [comment]
We were thinking of embedding a `codepen.io` example. I would start with this one: https://ol-kit.com/Map.html

Let us know if you have any questions

**Comment by UsmanAhmadSaeed** [comment]
Great, I'll try to get inspiration and learn on how to do this and possibly do it sometime.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
