### ISSUE TITLE
Add global action to bring back time slider if it was closed

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#209]
Only enable action if there is a time-enabled layer on the map

**Comment by ntatko** [comment]
I disagree with this, just for the record. It makes more sense for the implementing application to pass an `open` prop and an `onClose` callback, similarly to how [the material-ui `Dialog`](https://material-ui.com/components/dialogs/) handles being open or closed.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
