### ISSUE TITLE
Don't end Draw mode until the user specifically ends it

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#210]
AC:
- Recycle draw interaction instead of ending draw
- Wait for user to hit "Finish" before sending back array of new features
- Expand callback to return feature OR array
- Cancel removes all drawn features in mode from map
- Add property to allow IA to opt out of functionality
- Tests and docs

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
