### ISSUE TITLE
Make time slider draggable

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#211]
AC:

- [ ] Create DraggableBase to be ancestor of PopupBase
- [ ] DraggableBase manages draggable components
- [ ] Wrap time slider in new DraggableBase
- [ ] Tests and docs (of course)

**Comment by ntatko** [comment]
Implemented with https://github.com/Bayer-Group/ol-kit/pull/270

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
