### ISSUE TITLE
Add support for SyncableMap types alongside ol Maps

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#216]
This will be required to migrate internal Bayer apps and also support multi-maps in ol-kit

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
