### ISSUE TITLE
Enable TaffyDB search on doc pages

### ISSUE THREAD

**Issue by glenselle** [Bayer-Group/ol-kit#22]
Our JSdoc template has taffydb info in it. We need to look at how other doc sites enable search.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
