### ISSUE TITLE
Make translations file pure JSON

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#232]
Take out the version string import from package and make the entire file pure JSON for portability

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
