### ISSUE TITLE
Make popup work with vector tile layers

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#239]

**Comment by stazrad** [comment]
check here: https://github.com/MonsantoCo/ol-kit/blob/ef48ad570e4a3c5db0ada7f0b3d5508109cc0aab/src/Popup/utils.js#L88

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
