### ISSUE TITLE
Add a ship GH Action

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#24]
This should be a github action that allows you to choose `major`/`minor`/`patch` that bumps the `package.json` version on master, releases `release` doc on gh (which should create tag) and runs `npm run ship` to deploy new version to npm

**Comment by glenselle** [comment]
@AtherBilal

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
