### ISSUE TITLE
Determine why multiple maps on one page do not work

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#241]
Today if you embed multiple maps, one of them take control over all of them. Is this context/provider pollution?

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
