### ISSUE TITLE
Layer styler color picker doesn't extend off of the layerpanel/parent

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#265]
![image](https://user-images.githubusercontent.com/37306038/104111639-dd426a00-52a9-11eb-8579-3966005589c4.png)

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
