### ISSUE TITLE
TimeSlider does not have initial values if layer is added after TimeSlider rendered

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#267]
I think we need to add another event listener: somehow `onlayeradd` or `onfeatureadd`.

I know those don't exist within openlayers, but there might be something we can do on the time enabled layer.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
