### ISSUE TITLE
Too many checkboxes in new PR for external contributions

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#279]
There are 4 checkboxes when making a new PR

```
 - [ ] Added the task to the appropriate release doc under Enhancements or Bug Fixes
 - [ ] Bump package.json & package-lock.json version numbers to appropriate release
 - [ ] (optional) All external API changes have been documented
 - [ ] (optional) Build docs: npm run docs
```
1.) dope, that's a great thing to ask
2.) An external contributor SHOULD NOT ever bump `package.json`. 
3.) Yeah, agreed. Document changes. You might want to specify what an external API change is, in this case, though.
4.) Docs only need to be generated when shipping the docs, they don't need to be updated on every PR.

Can we update these?

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
