### ISSUE TITLE
Layer Panel chokes on layers with many children

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#280]
I have a layer with over 10,000 features on it. The map generally works fine. However, when attempting to hide that layer via the layer panel, the page crashes.

I think that the action item here, at least starting off, is either to not attempt to render features in the layer panel at some number of children, OR to virtualize the list (see [react-virtualized](https://www.npmjs.com/package/react-virtualized) for code and examples).

**Comment by stazrad** [comment]
Yes. This is a major problem...I was thinking just render a subset and continue to do so on scroll.

**Comment by ntatko** [comment]
> I was thinking just render a subset and continue to do so on scroll.

The trouble is, if you're looking for something at the bottom, you'd still end up with a bunch of elements on the page. Virtualization or pagination are the common solutions to this.

**Comment by ntatko** [comment]
If we fix #281, some of the pressure goes away here, then it will only choke when open.
