### ISSUE TITLE
LayerPanel is always mounted

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#281]
The layer panel being mounted causes really slow rendering on the map for large featuresets. It should not be trying to render features in the layer panel while off the screen. just unmount when it shows again...

**Comment by ntatko** [comment]
It shouldn't be rendering children, provided state is being updated correctly. I agree, this is a bug, but I can't think why it's doing this.

https://github.com/MonsantoCo/ol-kit/blob/76b1c55cd7344921a2822be8163c59ca1948ecb0/src/LayerPanel/LayerPanelBase/index.js#L52-L56
