### ISSUE TITLE
Have popup actions and details respect height of the popup

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#283]
Long ago in PFO, users requested a bigger popup, so we changed the popup parent to be bigger. However, the popup doesn't really like being bigger, and fails to show information beyond where it would regularly.

![Screen Shot 2021-02-26 at 1 33 15 PM](https://user-images.githubusercontent.com/37306038/109346579-854ecb00-7837-11eb-8c83-35e5265cfffa.png)

If it's possible, can we remove the `height: 169px` in favor of `height: auto`
https://github.com/MonsantoCo/ol-kit/blob/8547669bee493737ffd095853b3e8b844c787bbb/src/Popup/PopupInsert/PopupDefaultPage/index.js#L90

**Comment by kuberlog** [comment]
I'm failing to reproduce

<img width="579" alt="Screen Shot 2021-03-09 at 6 28 08 PM" src="https://user-images.githubusercontent.com/1966377/110556966-39d4d080-8105-11eb-82ec-f5cd09937eb1.png">

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternative solutions:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
