### ISSUE TITLE
Rain Viewer Precip Layer

### ISSUE THREAD

**Issue by code-johnny-code** [Bayer-Group/ol-kit#286]
Integrate with Rain Viewer to make a Precip Layer!
https://www.rainviewer.com

**Comment by ntatko** [comment]
It's really easy to tie into openweathermaps v1 raster tiles - and it's got lots of free requests https://openweathermap.org/api/weathermaps

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternative solutions:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
