### ISSUE TITLE
Url coordinates undefined catch

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#307]
If the lat/long are undefined or NaN throw a warning in the console and default to generic url without custom view coordinates

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternative solutions:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
