### ISSUE TITLE
Cannot read properties of null (reading 'getImageData')

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#359]
<img width="457" alt="Screen Shot 2021-11-16 at 3 05 40 PM" src="https://user-images.githubusercontent.com/17538943/142065628-02c6130a-d160-46fb-bb22-4e139ccc8dc1.png">

New error related to raster on ol-kit `1.17.0`

**Comment by gabe647** [comment]
This is fixed in ol-kit 1.18.0
