### ISSUE TITLE
Shp file import error

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#366]
<img width="610" alt="Screen Shot 2021-11-23 at 3 14 06 PM" src="https://user-images.githubusercontent.com/17538943/144121239-0e117b8e-2161-4bbd-8fb3-0ee8abfc255b.png">

**Comment by akuma1** [comment]
We are deprecating ol-kit.
You may consider using these alternative solutions.

- Use openlayer directly as recent versions of openlayer provides quite a bit of functionality out of box.
- Additionally , you can take a look at these [openlayer libraries](https://openlayers.org/3rd-party/).
