### ISSUE TITLE
Prototype Pollution / lodash

### ISSUE THREAD

**Issue by fredleput** [Bayer-Group/ol-kit#41]
Hi,
After installing ol-kit, i've got 3 high vulnerabilities related to loadah dependency. npm audit says it's patched in version >=4.17.12. So, i installed latest version ie : 4.17.15 but vulnerabilities are still there.
Any help appreciated !
thx,
Fred.

**Comment by glenselle** [comment]
Hey Fred, thanks for reporting this! Some of these issues stem from the fact that `ol-kit` is depending on OpenLayers `4.6.5` -- we plan to update very soon to use the latest version

**Comment by fredleput** [comment]
No problem !

**Comment by glenselle** [comment]
Leaving open til we resolve this

**Comment by drodenberg** [comment]
Looking into this now and it looks like one of our vulnerabilities from `babel-plugin-inline-react-svg` wont be fixed anytime soon... https://github.com/airbnb/babel-plugin-inline-react-svg/issues/45

**Comment by drodenberg** [comment]
Vorpal has 3 high vulnerabilities and I have a comment on this waiting to see if this will get resolved. https://github.com/dthree/vorpal/issues/331. Found this as a potential alternative to vorpal. https://github.com/drew-y/cliffy

**Comment by drodenberg** [comment]
Those are the only vulnerabilities I have left from what I see

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
