### ISSUE TITLE
Improve Canvas Testing

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#42]
use this as an example: https://github.com/openlayers/openlayers/blob/3014b68254be3ac0c4cfce9af41d90e2aa321a1b/test/spec/ol/map.test.js#L891

**Comment by PatchesMaps** [comment]
This might be relevant https://github.com/openlayers/openlayers/blob/v4.6.5/test/spec/ol/map.test.js#L559

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
