### ISSUE TITLE
Make sidebar dynamic to reduce file churn

### ISSUE THREAD

**Issue by glenselle** [Bayer-Group/ol-kit#48]
Making the sidebar dynamic so each page is not changed when components are added or removed

**Comment by UsmanAhmadSaeed** [comment]
Hey, I'd like to try it. Can you provide some guidelines on how and where to? Is it docs related?

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
