### ISSUE TITLE
Strange scrolling on docs site

### ISSUE THREAD

**Issue by ntatko** [Bayer-Group/ol-kit#60]
Appears to happen when sidebar is longer than the body of the page, which, as more features get added, will become more and more common.

**Comment by UsmanAhmadSaeed** [comment]
@stazrad I'd like to give this one a try too.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
