### ISSUE TITLE
Host past versions of docs for easier dev access

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#73]

**Comment by UsmanAhmadSaeed** [comment]
How about this one? Can I take it too? and some guidelines.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
