### ISSUE TITLE
Create open dataset layer search utility

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#81]
Dependent on #80 and #82 

- [ ] Local search of hard-coded sources that work with demo site (today, GeoJSON and KML sources)
- [ ] Selecting layer loads it to the map
- [ ] Implement [Material UI Drawer component](https://material-ui.com/components/drawers/)
- [ ] Docs and tests

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
