### ISSUE TITLE
Add GeoServer Layer utility

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#87]
- [x] Move `GeoserverLayer` class from internal
- [x] Move supporting classes to wrap WFS and WMS layer calls from internal
- [ ] Add any missing jsdoc comments 
- [ ] Add usage examples

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
