### ISSUE TITLE
Shareable Projects

### ISSUE THREAD

**Issue by stazrad** [Bayer-Group/ol-kit#92]
it would be awesome to store map/layer style/state via an encoded url param that is parsed on page load and hydrates the map

- here's a good algorithm that outputs a very short string: [Block TEA](https://www.movable-type.co.uk/scripts/tea-block.html)
- [javascript implementation of above algorithm](https://github.com/chrisveness/crypto/blob/master/tea-block.js)

**Comment by glenselle** [comment]
What if we just encode everything as geojson for a simple project file format? You could download and upload projects without query params limiting the amount of data you can work with.
