### ISSUE TITLE
Allow basemap picker to preview maps at current extent

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#95]
To help the users identify which basemap would be best for the current view, we could try to show mini maps with the basemap picker at the current extent.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
