### ISSUE TITLE
Add URL query params to load basemap and other map data

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#97]
This would be a URL-based implementation of a project

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
